// app/signin/page.tsx
"use client";

import { useAuthActions } from "@convex-dev/auth/react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Navbar, Card, Label, TextInput, Checkbox, Button } from 'flowbite-react';
import Link from 'next/link';
import Image from "next/image";

export default function SignIn() {
  const { signIn } = useAuthActions();
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();
  return (
    <section className="bg-white dark:bg-gray-900">
      <Navbar fluid rounded>
        <Link href="/" className="flex items-center">
          <Image src="/pulseloop.svg" width={36} height={36} className="mr-3 h-9 w-9" alt="PulseLoop" />
          <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">PulseLoop</span>
        </Link>
      </Navbar>
      <div className="flex flex-col items-center justify-center min-h-screen px-6 py-8 mx-auto lg:py-0">
        <Card className="w-full bg-white rounded-2xl shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
          <div className="space-y-4 md:space-y-6">
            <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
              Welcome to PulseLoop
            </h1>
            <form 
              className="space-y-4 md:space-y-6"
              onSubmit={(e) => {
                e.preventDefault();
                const formData = new FormData(e.target as HTMLFormElement);
                formData.set("flow", "signIn")
                void signIn("password", formData)
                  .catch((error) => {
                    setError(error.message);
                  })
                  .then(() => {
                    router.push("/");
                  });
              }}            
            >
              <div>
                <div className="mb-2 block">
                  <Label htmlFor="email">Email</Label>
                </div>
                <TextInput id="email" name="email" placeholder="Enter your email" required type="email" />
              </div>
              <div>
                <div className="mb-2 block">
                  <Label htmlFor="password">Password</Label>
                </div>
                <TextInput id="password" name="password" placeholder="••••••••" required type="password" />
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-start">
                  <Checkbox id="remember" />
                  <Label htmlFor="remember" className="ml-2">Remember me</Label>
                </div>
                <a href="#" className="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Lost Password?</a>
              </div>
              <Button className="w-full" type="submit">Sign In</Button>
              <p className="text-sm font-light text-gray-500 dark:text-gray-400">
                Don’t have an account? <a href="/signup" className="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign Up</a>
              </p>
              {error && (
                <div className="bg-red-500/20 border-2 border-red-500/50 rounded-md p-2">
                  <p className="text-foreground font-mono text-xs">
                    Error signing in: {error}
                  </p>
                </div>
              )}
            </form>
          </div>
        </Card>
      </div>
    </section>
  );
}

// src/routes/signin/+page.svelte
<script lang="ts">
	import { useAuth } from '@mmailaender/convex-auth-svelte/sveltekit';
	import { goto } from '$app/navigation';
	import { Navbar, Card, Label, Input, Checkbox, Button } from 'flowbite-svelte';
	import logo from '$lib/assets/favicon.svg';

	const { signIn } = useAuth();

	let error: string | null = $state(null);
	let submitting = $state(false);
	let email = $state('');
	let password = $state('');
	let remember = $state(false);

	function handleEmailSignIn(email: string, password: string) {
		return signIn('password', {
			flow: 'signIn',
			email: email,
			password: password
		});
	}

	async function handleSubmit(e: Event) {
		e.preventDefault();
		error = null;
		submitting = true;

		try {
			await handleEmailSignIn(email, password);
			goto('/');
		} catch (err: any) {
			if (err?.message) {
				error = err.message;
			} else {
				error = 'An unexpected error occurred. Please try again';
			}
		} finally {
			submitting = false;
		}
	}
</script>

<section class="bg-white dark:bg-gray-900">
	<Navbar>
		<a href="/" class="flex items-center">
			<img src={logo} class="mr-3 h-9 w-9" alt="PulseLoop" />
			<span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"
				>PulseLoop</span
			>
		</a>
	</Navbar>

	<div class="mx-auto flex min-h-screen flex-col items-center justify-center px-6 py-8 lg:py-0">
		<Card
			class="w-full rounded-2xl bg-white p-6 shadow sm:max-w-md md:mt-0 xl:p-0 dark:border dark:border-gray-700 dark:bg-gray-800"
		>
			<div class="space-y-4 md:space-y-6">
				<h1
					class="text-xl leading-tight font-bold tracking-tight text-gray-900 md:text-2xl dark:text-white"
				>
					Welcome to PulseLoop
				</h1>

				<form class="space-y-4 md:space-y-6" onsubmit={handleSubmit}>
					<div>
						<div class="mb-2 block">
							<Label for="email">Email</Label>
						</div>
						<Input
							id="email"
							bind:value={email}
							placeholder="Enter your email"
							required
							type="email"
						/>
					</div>

					<div>
						<div class="mb-2 block">
							<Label for="password">Password</Label>
						</div>
						<Input
							id="password"
							bind:value={password}
							placeholder="••••••••"
							required
							type="password"
						/>
					</div>

					<div class="flex items-center justify-between">
						<div class="flex items-start">
							<Checkbox id="remember" bind:checked={remember} />
							<Label for="remember" class="ml-2">Remember me</Label>
						</div>
						<a
							href="#"
							class="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500"
						>
							Lost Password?
						</a>
					</div>

					<Button class="w-full" type="submit" disabled={submitting}>
						{submitting ? 'Signing in...' : 'Sign In'}
					</Button>

					<p class="text-sm font-light text-gray-500 dark:text-gray-400">
						Don't have an account?
						<a
							href="/signup"
							class="font-medium text-primary-600 hover:underline dark:text-primary-500"
						>
							Sign Up
						</a>
					</p>

					{#if error}
						<div class="rounded-md border-2 border-red-500/50 bg-red-500/20 p-2">
							<p class="text-foreground font-mono text-xs">
								Error signing in: {error}
							</p>
						</div>
					{/if}
				</form>
			</div>
		</Card>
	</div>
</section>
